'use client';
import {useEffect,useRef,useState} from 'react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {flushSync} from 'react-dom';
import {prepareMessage} from '@/lib/message.mjs';
import {Arrow} from '@/components/reveal';
const topics=['Persoonlijke begeleiding','Voor mijn organisatie','Foundation'];
export function ContactForm(){
 const [ready,setReady]=useState(false); const [topic,setTopic]=useState(topics[0]); const [detail,setDetail]=useState(''); const [draft,setDraft]=useState(''); const [feedback,setFeedback]=useState(''); const output=useRef<HTMLDivElement>(null);
 useEffect(()=>{const id=window.requestAnimationFrame(()=>{setReady(true);const value=new URLSearchParams(window.location.search).get('onderwerp');if(value){setDetail(value);setTopic(value==='Bedrijfsvitaliteit'?topics[1]:['Samenwerken','Bijdragen'].includes(value)?topics[2]:topics[0]);}});return()=>window.cancelAnimationFrame(id);},[]);
 function showDraft(input:unknown){const text=prepareMessage(input);flushSync(()=>{setDraft(text);setFeedback('');});output.current?.focus();return text;}
 function prepare(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{showDraft({name:data.get('name'),message:data.get('message'),email:data.get('email')||'',topic:detail||topic});}catch(error){setFeedback(error instanceof Error?error.message:'Controleer je invoer.');}}
 useEffect(()=>{
   type Context={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>unknown};
   const context=(document as Document & {modelContext?:Context}).modelContext;
   if(!context?.registerTool)return;
   const lifecycle=new AbortController();
   try{Promise.resolve(context.registerTool({name:'prepare_reveal_message',title:'Reveal It conceptbericht voorbereiden',description:'Stel een lokaal conceptbericht samen en toon het op de pagina. Verstuurt niets en boekt niets.',inputSchema:{type:'object',properties:{name:{type:'string',maxLength:100},message:{type:'string',minLength:10,maxLength:2500},topic:{type:'string',maxLength:100},email:{type:'string',maxLength:150}},required:['name','message'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{showDraft(input);return {status:'draft',sent:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
   return ()=>lifecycle.abort();
 },[]);
 async function copy(){try{await navigator.clipboard.writeText(draft);setFeedback('Gekopieerd. Je kunt het bericht zelf bewaren of later versturen.');}catch{setFeedback('Kopiëren is hier niet beschikbaar. Selecteer de tekst of download je bericht.');}}
 return <div className="contact-form-shell"><noscript><p className="notice">Zet JavaScript aan om een conceptbericht samen te stellen. Deze website verstuurt geen berichten.</p></noscript><form onSubmit={prepare} className="contact-form"><fieldset disabled={!ready} className="form-controls"><fieldset><legend>Waar gaat je vraag over?</legend><RadioGroup className="topic-options" value={topic} onValueChange={v=>{setTopic(v);setDetail('');}} aria-label="Onderwerp van je vraag">{topics.map((item,i)=><label key={item} htmlFor={'topic-'+i} className={topic===item?'selected':''}><RadioGroupItem id={'topic-'+i} value={item}/>{item}</label>)}</RadioGroup></fieldset>{detail&&<p className="chosen-service">Gekozen: <strong>{detail}</strong></p>}<label htmlFor="name">Je naam <span>(verplicht)</span></label><input id="name" name="name" autoComplete="name" maxLength={100} required placeholder="Hoe heet je?"/><label htmlFor="email">E-mailadres <span>(optioneel)</span></label><input id="email" name="email" type="email" autoComplete="email" maxLength={150} placeholder="jij@voorbeeld.nl"/><label htmlFor="message">Wat wil je bespreken? <span>(verplicht)</span></label><textarea id="message" name="message" rows={5} required minLength={10} maxLength={2500} placeholder="Vertel kort wat je zoekt of wilt bereiken."/><p className="field-note">Minimaal 10 tekens. Deel hier geen medische of andere gevoelige gegevens.</p><button className="button" type="submit">Bekijk je conceptbericht <Arrow/></button><p className="field-note">Alles blijft in dit venster. Er wordt niets verzonden of opgeslagen. <a href="/privacy">Over je privacy</a></p></fieldset></form>{draft&&<div className="draft-preview" ref={output} tabIndex={-1}><p className="eyebrow plain">JOUW CONCEPTBERICHT</p><h2>Klaar om te bewaren</h2><p>Dit bericht is niet verstuurd. Bewaar het voor je kennismaking.</p><label htmlFor="draft">Je kunt de tekst hieronder aanpassen.</label><textarea id="draft" value={draft} onChange={e=>setDraft(e.target.value)} rows={10}/><div className="actions"><a className="button" href={"data:text/plain;charset=utf-8,"+encodeURIComponent(draft)} download="reveal-it-conceptbericht.txt" onClick={()=>setFeedback("Download aangevraagd. Het bericht is niet verstuurd. Je kunt de tekst ook kopiëren.")}>Download bericht</a><button className="text-link" onClick={copy} type="button">Kopieer tekst</button></div></div>}<p className="form-feedback" role="status">{feedback}</p></div>
}
