import type {ReactNode} from 'react';
import Link from 'next/link';
export function Arrow(){return <svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none"><path d="M4 12h15M13 5l7 7-7 7" stroke="currentColor" strokeWidth="1.5"/></svg>}
export function SectionLabel({children}:{children:ReactNode}){return <p className="eyebrow"><span aria-hidden="true"/>{children}</p>}
export function LinkButton({href,children,light=false}:{href:string;children:ReactNode;light?:boolean}){return <Link className={`button ${light?'button-light':''}`} href={href}>{children}<Arrow/></Link>}
export function Wordmark(){return <span className="wordmark">reveal<span className="wordmark-it">it</span><span className="wordmark-period">.</span></span>}
export function Header(){return <header className="site-header wrap"><Link className="brand" href="/" aria-label="Reveal It, home"><Wordmark/></Link><nav className="desktop-nav" aria-label="Hoofdnavigatie"><Link href="/#over">Onze aanpak</Link><Link href="/reveal-fit">Reveal Fit</Link><Link href="/foundation">Foundation</Link></nav><Link className="header-contact" href="/contact">Laten we kennismaken <Arrow/></Link><details className="mobile-menu"><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Mobiele navigatie"><Link href="/">Home</Link><Link href="/#over">Onze aanpak</Link><Link href="/reveal-fit">Reveal Fit</Link><Link href="/foundation">Foundation</Link><Link href="/contact">Kennismaken</Link></nav></details></header>}
export function Footer(){return <footer className="site-footer"><div className="wrap"><div className="footer-top"><div><Link className="brand" href="/" aria-label="Reveal It, home"><Wordmark/></Link><p>Discipline builds destiny.</p></div><nav aria-label="Footernavigatie"><Link href="/reveal-fit">Reveal Fit</Link><Link href="/foundation">Foundation</Link><Link href="/foundation/anbi">ANBI-informatie</Link><Link href="/contact">Contact</Link></nav></div><div className="footer-bottom"><span>© 2026 Reveal It</span><span>Beelden zijn illustratieve sfeerbeelden.</span><Link href="/privacy">Privacy</Link><span className="preview-label">Conceptwebsite</span></div></div></footer>}
export function Breadcrumb({current}:{current:string}){return <nav className="breadcrumb" aria-label="Broodkruimel"><Link href="/">Reveal It</Link><span aria-hidden="true">/</span><span aria-current="page">{current}</span></nav>}
