/* eslint-disable @next/next/no-html-link-for-pages -- GitHub Pages export needs hard navigations with trailing-slash URLs. */
import type {ReactNode} from 'react';
export function Arrow(){return <svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none"><path d="M4 12h15M13 5l7 7-7 7" stroke="currentColor" strokeWidth="1.5"/></svg>}
export function SectionLabel({children}:{children:ReactNode}){return <p className="eyebrow"><span aria-hidden="true"/>{children}</p>}
export function LinkButton({href,children,light=false}:{href:string;children:ReactNode;light?:boolean}){return <a className={`button ${light?'button-light':''}`} href={href}>{children}<Arrow/></a>}
export function Wordmark(){return <span className="wordmark">reveal<span className="wordmark-it">it<span className="wordmark-period" aria-hidden="true"/></span></span>}
export function Header(){return <header className="site-header wrap"><a className="brand" href="/" aria-label="Reveal It, home"><Wordmark/></a><nav className="desktop-nav" aria-label="Hoofdnavigatie"><a href="/#over">Onze aanpak</a><a href="/reveal-fit/">Reveal Fit</a><a href="/foundation/">Foundation</a></nav><a className="header-contact" href="/contact/">Laten we kennismaken <Arrow/></a><details className="mobile-menu"><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Mobiele navigatie"><a href="/">Home</a><a href="/#over">Onze aanpak</a><a href="/reveal-fit/">Reveal Fit</a><a href="/foundation/">Foundation</a><a href="/contact/">Kennismaken</a></nav></details></header>}
export function Footer(){return <footer className="site-footer"><div className="wrap"><div className="footer-top"><div><a className="brand" href="/" aria-label="Reveal It, home"><Wordmark/></a><p>Discipline builds destiny.</p></div><nav aria-label="Footernavigatie"><a href="/reveal-fit/">Reveal Fit</a><a href="/foundation/">Foundation</a><a href="/foundation/anbi/">ANBI-informatie</a><a href="/contact/">Contact</a></nav></div><div className="footer-bottom"><span>© 2026 Reveal It</span><span>Beelden zijn illustratieve sfeerbeelden.</span><a href="/privacy/">Privacy</a><span className="preview-label">Conceptwebsite</span></div></div></footer>}
export function Breadcrumb({current}:{current:string}){return <nav className="breadcrumb" aria-label="Broodkruimel"><a href="/">Reveal It</a><span aria-hidden="true">/</span><span aria-current="page">{current}</span></nav>}
